# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 06:55
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('tag', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('content', models.TextField()),
                ('time', models.DateField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'blog',
                'ordering': ('time',),
            },
        ),
    ]
